name: Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md']
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore: [ '**.md' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Execute Tests, Code Coverage and Publish Results to Sonar
        run: mvn -B verify jacoco:report sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=leonardozv -Dsonar.projectName=spark-connectors-parent -Dsonar.projectKey=com.leonardozv:spark-connectors-parent -Dsonar.qualitygate.wait
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}