name: Continuous Delivery

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy --file pom.xml --batch-mode pitest:mutationCoverage jacoco:report sonar:sonar -Dsonar.host.url=http://leozvasconcellos-sonarqube.eastus.azurecontainer.io:9000/ -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=com.leonardozv:spark-connectors  -Dsonar.branch.name=${{ github.ref_name }} -Dsonar.qualitygate.wait
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update dependency graph for Dependabot
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6