name: Java CI with Maven

on:
  push:
    branches:
      - master
    paths:
      - spark-connectors-aws-sqs/**

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'corretto'
        - name: Execute Tests, Code Coverage, Mutation Testing and Publish Results to Sonar
          run: mvn test jacoco:report sonar:sonar -Dsonar.host.url=http://leozvasconcellos-sonarqube.eastus.azurecontainer.io:9000/ -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=${{ github.repository_owner }}_spark-connectors-aws-sqs -Dsonar.qualitygate.wait --batch-mode --file pom.xml